### PR TITLE
add spdx headers and fix copyright headers

### LINKED ISSUE #3: spdx headers
for the purposes of upstreaming, all new files need the spdx license header comment. Then we should add the copyright of the previous authors to each header (ie. @xerpi).

### PR DESCRIPTION
**Pull request by Wolfvak**
fixes #3

### CODE REVIEW

File: drivers/platform/nintendo3ds/ctr_pxi.h [hunk 1]
```diff
@@ -1,5 +1,17 @@
...
+ *  ctr_pxi.c
+ *
+ *  Copyright (C) 2020-2021 Santiago Herrera
+ *
+ *  Based on virtio_mmio.c
+ *
+ * This program is free software; you can redistribute it and/or modify
+ * it under the terms of the GNU General Public License version 2 as
+ * published by the Free Software Foundation.
+ */
```
Comment (nickdesaulniers) [inline drivers/platform/nintendo3ds/ctr_pxi.h:12]: you should cut these blocks out; they're covered by the SPDX header

**Review by nickdesaulniers — COMMENTED** [review]
As part of this cleanup, we should add SPDX header, but also remove the blocks:

```
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
```
as that's implied by the SPDX headers.  The SPDX headers are meant to be a more concise way of denoting the license that that whole block of text at the top of every new file.

**Comment by Wolfvak** [comment]
added those too

**Review by nickdesaulniers — APPROVED** [review]
